# ==UserScript==
# @ConfigName        è‡ªç”¨Clashé…ç½®
# @Author            @HLiu
# @UpdateTime        2023/04/21
# @Function          æ”¯æŒæ‰‹åŠ¨é€‰æ‹©ã€è‡ªåŠ¨æµ‹é€Ÿã€å¹¿å‘Šå±è”½ã€å…œåº•åˆ†æµã€æŒ‰å›½å®¶åˆ†ç»„èŠ‚ç‚¹ç­‰ç­‰   
# @ClashDownload     https://github.com/Fndroid/clash_for_windows_pkg/releases
# @Attention         è¯·ä½¿ç”¨æœ€æ–°ç‰ˆClashforWindows
# @ConfigVersion     1.0.3
# ==/UserScript==      

port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - msftconnecttest.com
    - xbox.*.microsoft.com
    - "*.battlenet.com.cn"
    - "*.battlenet.com"
    - "*.blzstatic.cn"
    - "*.battle.net"
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
  fallback:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
pr:
  &a2
  type: select
  proxies:
    - DIRECT
    - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    - ğŸš€ è‡ªåŠ¨é€‰æ‹©
    - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
p:
  &a1
  type: http
  interval: 86400
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 1800
auto:
  &a3
  type: url-test
  lazy: true
  url: http://www.gstatic.com/generate_204
  interval: 900
  use:
    - Subscribe
use:
  &a4
  type: select
  use:
    - Subscribe
c:
  &a6
  type: http
  behavior: classical
  interval: 86400
d:
  &a5
  type: http
  behavior: domain
  interval: 86400
i:
  &a7
  type: http
  behavior: ipcidr
  interval: 86400
proxy-providers:
  Subscribe:
    <<: *a1
    url: https://sub.xeton.dev/sub?target=clash&url=https://s.trojanflare.com/clashx/7551b9d6-0380-4a9d-a616-52d5c2700b57&list=true&udp=false
    path: ./proxy_providers/tmp.yaml
proxies: null
proxy-groups:
  - name: ğŸŒ å…¨çƒåŠ é€Ÿ
    <<: *a2
  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    <<: *a3
    filter: ç¾|US|(?i)States|American
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    <<: *a3
    filter: æ—¥|ä¸œäº¬|JP|(?i)Japan
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    <<: *a3
    filter: æ¸¯|HK|(?i)Hong
  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    <<: *a4
  - name: ğŸš€ è‡ªåŠ¨é€‰æ‹©
    <<: *a3
  - name: ğŸ è‹¹æœæœåŠ¡
    <<: *a2
  - name: ğŸ¤– å¾®è½¯æœåŠ¡
    <<: *a2
  - name: ğŸŒŒ è°·æ­ŒæœåŠ¡
    <<: *a2
  - name: ğŸ¬ å›½é™…åª’ä½“
    <<: *a2
  - name: ğŸ“Ÿ ç”µæŠ¥æ¶ˆæ¯
    <<: *a2
  - name: ğŸŸ å…œåº•åˆ†æµ
    <<: *a2
  - name: ğŸ† AdBlock
    type: select
    proxies:
      - REJECT
rule-providers:
  Direct:
    <<: *a5
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Direct/Direct.yaml
    path: ./ruleset/Direct.yaml
  Lan:
    <<: *a6
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.yaml
    path: ./ruleset/Lan.yaml
  Download:
    <<: *a6
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Download/Download.yaml
    path: ./ruleset/Download.yaml
  Ad:
    <<: *a5
    url: https://anti-ad.net/clash.yaml
    path: ./ruleset/anti-ad-clash.yaml
  GlobalMedia:
    <<: *a6
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml
    path: ./ruleset/GlobalMedia.yaml
  Apple:
    <<: *a6
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple_Classical.yaml
    path: ./ruleset/Apple.yaml
  Github:
    <<: *a6
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml
    path: ./ruleset/Github.yaml
  Google:
    <<: *a6
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml
    path: ./ruleset/Google.yaml
  Telegram:
    <<: *a6
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml
    path: ./ruleset/Telegram.yaml
  Microsoft:
    <<: *a6
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./ruleset/Microsoft.yaml
  ChinaIP:
    <<: *a7
    url: https://cdn.jsdelivr.net/gh/soffchen/GeoIP2-CN@release/clash-rule-provider.yml
    path: ./ruleset/ChinaIP.yaml
  ProxyLite:
    <<: *a6
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ProxyLite/ProxyLite.yaml
    path: ./ruleset/ProxyLite.yaml
rules:
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Lan,DIRECT
  - RULE-SET,Download,DIRECT
  - RULE-SET,Ad,ğŸ† AdBlock
  - RULE-SET,GlobalMedia,ğŸ¬ å›½é™…åª’ä½“
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Github,ğŸŒ å…¨çƒåŠ é€Ÿ
  - RULE-SET,Google,ğŸŒŒ è°·æ­ŒæœåŠ¡
  - RULE-SET,Telegram,ğŸ“Ÿ ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,Microsoft,ğŸ¤– å¾®è½¯æœåŠ¡
  - RULE-SET,ProxyLite,ğŸŒ å…¨çƒåŠ é€Ÿ
  - RULE-SET,ChinaIP,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ğŸŸ å…œåº•åˆ†æµ
